backupUser: backup
backupUserID: 34
backupUserGroup: backup
backupUserGID: 34
backupUserLoginAuthorizedKey: <drop your key>
backupMountPoint: /backup
backupMountType: nfs
backupRemoteHost: dwlab-central-01.dw-lab.de
backupRemoteDir: /data/backup
backupFileServerUser: <Username>
backupFileServerPassword: <as required>
