backupUser: backup
backupUserID: 34
backupUserGroup: backup
backupUserGID: 34
backupUserLoginAuthorizedKey: <drop your key>
backupMountPoint: <mountPoint>
backupMountType:  local | smb | nfs
backupRemoteHost: <Hostame with FQDN> | <IP-Address>
backupRemoteDir: /backup/checkmk
backupFileServerUser: <Username>
backupFileServerPassword: <as required>
